import { cva } from "class-variance-authority";

export const gridStyles = cva(["grid"], {
  variants: {
    columns: {
      1: "grid-cols-1",
      2: "grid-cols-2",
      3: "grid-cols-3",
      4: "grid-cols-4",
      5: "grid-cols-5",
      6: "grid-cols-6",
      7: "grid-cols-7",
      8: "grid-cols-8",
      9: "grid-cols-9",
      10: "grid-cols-10",
      11: "grid-cols-11",
      12: "grid-cols-12",
    },
    rows: {
      1: "grid-rows-1",
      2: "grid-rows-2",
      3: "grid-rows-3",
      4: "grid-rows-4",
      5: "grid-rows-5",
      6: "grid-rows-6",
      7: "grid-rows-7",
      8: "grid-rows-8",
      9: "grid-rows-9",
      10: "grid-rows-10",
      11: "grid-rows-11",
      12: "grid-rows-12",
    },
    spacing: {
      none: "gap-0",
      small: "gap-2",
      medium: "gap-4",
      large: "gap-6",
    },
    rowSpacing: {
      none: "",
      small: "gap-y-2",
      medium: "gap-y-4",
      large: "gap-y-6",
    },
    columnSpacing: {
      none: "",
      small: "gap-x-2",
      medium: "gap-x-4",
      large: "gap-x-6",
    },
  },
});

export const gridItemStyles = cva([], {
  variants: {
    columnSpan: {
      0: "col-span-auto",
      1: "col-span-1",
      2: "col-span-2",
      3: "col-span-3",
      4: "col-span-4",
      5: "col-span-5",
      6: "col-span-6",
      7: "col-span-7",
      8: "col-span-8",
      9: "col-span-9",
      10: "col-span-10",
      11: "col-span-11",
      12: "col-span-12",
    },
    rowSpan: {
      0: "row-span-auto",
      1: "row-span-1",
      2: "row-span-2",
      3: "row-span-3",
      4: "row-span-4",
      5: "row-span-5",
      6: "row-span-6",
      7: "row-span-7",
      8: "row-span-8",
      9: "row-span-9",
      10: "row-span-10",
      11: "row-span-11",
      12: "row-span-12",
    },
    rowOffset: {
      0: "row-start-auto",
      1: "row-start-1",
      2: "row-start-2",
      3: "row-start-3",
      4: "row-start-4",
      5: "row-start-5",
      6: "row-start-6",
      7: "row-start-7",
      8: "row-start-8",
      9: "row-start-9",
      10: "row-start-10",
      11: "row-start-11",
      12: "row-start-12",
      13: "row-start-13",
    },
    columnOffset: {
      0: "col-start-auto",
      1: "col-start-1",
      2: "col-start-2",
      3: "col-start-3",
      4: "col-start-4",
      5: "col-start-5",
      6: "col-start-6",
      7: "col-start-7",
      8: "col-start-8",
      9: "col-start-9",
      10: "col-start-10",
      11: "col-start-11",
      12: "col-start-12",
      13: "col-start-13",
    },
  },
});
